#!/usr/bin/env python3
"""Summarize late-fusion modality weights (w_H, w_W, w_G; sum=1) from a fusion run."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUN = REPO_ROOT / "classification_results/run_late_fusion_ddk/all_fold_metrics.csv"

LANG_MAP = {
    "German": "DE",
    "Czech": "CZ",
    "Colombian": "ES",
}


def _lang_from_csv(csv_file: str) -> str:
    for name, code in LANG_MAP.items():
        if name in csv_file:
            return code
    return "UNK"


def _fmt(mean: float, std: float) -> str:
    return f"{mean:.2f}±{std:.2f}"


def summarize(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["language"] = df["csv_file"].map(_lang_from_csv)
    rows = []
    group_cols = ["fusion", "language", "model"]
    for keys, g in df.groupby(group_cols, sort=False):
        fusion, lang, model = keys
        rows.append(
            {
                "fusion": fusion,
                "language": lang,
                "model": model.upper(),
                "w_hubert_mean": g["w_hubert"].mean(),
                "w_hubert_std": g["w_hubert"].std(),
                "w_whisper_mean": g["w_whisper"].mean(),
                "w_whisper_std": g["w_whisper"].std(),
                "w_glottal_mean": g["w_glottal"].mean(),
                "w_glottal_std": g["w_glottal"].std(),
                "n_folds": len(g),
            }
        )
    out = pd.DataFrame(rows)
    order = ["LF-H+W+G", "LF-H+W-FT+G", "LF-H+W-CTC+G"]
    out["fusion"] = pd.Categorical(out["fusion"], categories=order, ordered=True)
    out["language"] = pd.Categorical(out["language"], categories=["CZ", "DE", "ES"], ordered=True)
    return out.sort_values(["fusion", "language", "model"]).reset_index(drop=True)


def to_markdown(summary: pd.DataFrame) -> str:
    lines = [
        "# Late-fusion weights (mean ± std over 10 outer CV folds)",
        "",
        "Weights optimize speaker-level ROC-AUC on inner CV (grid step 0.1, Σw = 1).",
        "",
        "| Fusion | Lang | Clf. | w_H (HuBERT) | w_W (Whisper) | w_G (glottal) |",
        "|--------|------|------|--------------|---------------|---------------|",
    ]
    for _, r in summary.iterrows():
        lines.append(
            f"| {r['fusion']} | {r['language']} | {r['model']} | "
            f"{_fmt(r['w_hubert_mean'], r['w_hubert_std'])} | "
            f"{_fmt(r['w_whisper_mean'], r['w_whisper_std'])} | "
            f"{_fmt(r['w_glottal_mean'], r['w_glottal_std'])} |"
        )
    lines.append("")
    return "\n".join(lines)


def to_latex(summary: pd.DataFrame, label: str = "tab:late_fusion_weights") -> str:
    lines = [
        "% Auto-generated by scripts/summarize_late_fusion_weights.py",
        "\\begin{table}[!t]",
        "\\caption{Late-fusion weights tuned on inner CV (speaker-level ROC-AUC; "
        "$\\sum w = 1$; grid step 0.1). Mean $\\pm$ std over 10 outer folds.}",
        f"\\label{{{label}}}",
        "\\centering",
        "\\footnotesize",
        "\\begin{tabular}{|l|l|l|c|c|c|}",
        "\\hline",
        "\\textbf{Fusion} & \\textbf{Lang.} & \\textbf{Clf.} & "
        "\\textbf{$w_H$} & \\textbf{$w_W$} & \\textbf{$w_G$} \\\\",
        "\\hline",
    ]
    prev_fusion = None
    for _, r in summary.iterrows():
        if prev_fusion is not None and r["fusion"] != prev_fusion:
            lines.append("\\hline")
        fusion_cell = str(r["fusion"]) if r["fusion"] != prev_fusion else ""
        lines.append(
            f"{fusion_cell} & {r['language']} & {r['model']} & "
            f"{_fmt(r['w_hubert_mean'], r['w_hubert_std'])} & "
            f"{_fmt(r['w_whisper_mean'], r['w_whisper_std'])} & "
            f"{_fmt(r['w_glottal_mean'], r['w_glottal_std'])} \\\\"
        )
        prev_fusion = r["fusion"]
    lines.extend(["\\hline", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fold-metrics",
        type=Path,
        default=DEFAULT_RUN,
        help="Path to all_fold_metrics.csv from late_fusion_ddk.py",
    )
    parser.add_argument(
        "--write-md",
        action="store_true",
        help="Write classification_results/late_fusion_weights.md",
    )
    parser.add_argument(
        "--write-latex",
        action="store_true",
        help="Write classification_results/late_fusion_weights.tex",
    )
    parser.add_argument(
        "--write-csv",
        action="store_true",
        help="Write classification_results/late_fusion_weights_summary.csv",
    )
    args = parser.parse_args()

    if not args.fold_metrics.is_file():
        raise SystemExit(
            f"Missing {args.fold_metrics}\n"
            "Run late fusion first:\n"
            "  python3 late_fusion_ddk.py --presets LF-H+W+G,LF-H+W-FT+G,LF-H+W-CTC+G"
        )

    df = pd.read_csv(args.fold_metrics)
    summary = summarize(df)

    if not (args.write_md or args.write_latex or args.write_csv):
        print(to_markdown(summary))
        return

    out_dir = REPO_ROOT / "classification_results"
    if args.write_csv:
        path = out_dir / "late_fusion_weights_summary.csv"
        summary.to_csv(path, index=False)
        print(f"Wrote {path}")
    if args.write_md:
        path = out_dir / "late_fusion_weights.md"
        path.write_text(to_markdown(summary), encoding="utf-8")
        print(f"Wrote {path}")
    if args.write_latex:
        path = out_dir / "late_fusion_weights.tex"
        path.write_text(to_latex(summary), encoding="utf-8")
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
